apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-pod
  type: ClusterIP
  ports:
    - port: 5001 #listens here
      targetPort: 5000 #forwards requests here.
      protocol: TCP
