apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_ROOT_PASSWORD: QXV0aDEyMw==  # base64 encoded value of "Auth123" and username is 'root'.
  MYSQL_DATABASE: YXV0aA==      # base64 encoded value of "auth"