apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment #name of deployment itself
  labels:
    app: gateway #label applied to deployment itself. Can be used to select this deployment using Kubernetes selector.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-pod  #should match with pod-name as it tells which pods are part of deployment.
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: gateway-pod #This is the pod-name. 
    spec:
      containers:
        - name: gateway-container  #This is the name of the container within a pod.
          image: swapnilthejain/gateway
          ports:
            - containerPort: 8080 #tells what port is being exposed by the container. Just for documentation purposes.
          envFrom:
            - configMapRef:
                name: gateway-configmap
            - secretRef:
                name: gateway-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"