apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-pod # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: rabbitmq-pod # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: rabbitmq-container
          image: rabbitmq:3-management  #official rabbitmq image with a GUI.
          ports:
            - name: http
              protocol: TCP
              containerPort: 15672 #port that handles GUI 
            - name: amqp   #stands for advanced message queuing protocol, used to send queue message.
              protocol: TCP
              containerPort: 5672  #port that handles the actual queue.
          envFrom:
            - configMapRef:
                name: rabbitmq-configmap
            - secretRef:
                name: rabbitmq-secret
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: "/var/lib/rabbitmq"  #path WITHIN container(pod) where data will stored. We need to mount an ACTUAL storage to this path.
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc